#!/usr/bin/env bash
#
# Deploy the crowdfunding dApp to a Stellar network (default: testnet).
#
# Steps:
#   1. Ensure a funded deployer identity exists.
#   2. Build the contracts to WASM.
#   3. Upload the campaign WASM and capture its hash.
#   4. Deploy the factory, passing the admin + campaign WASM hash to its
#      constructor.
#   5. Deploy a test USDC asset (SAC) so the frontend has a token to use.
#   6. Write the resulting IDs into frontend/.env.local.
#
# Usage:
#   ./scripts/deploy.sh                 # testnet, identity "crowdfund"
#   NETWORK=testnet IDENTITY=alice ./scripts/deploy.sh
#
set -euo pipefail

NETWORK="${NETWORK:-testnet}"
IDENTITY="${IDENTITY:-crowdfund}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WASM_DIR="$ROOT/target/wasm32v1-none/release"
ENV_FILE="$ROOT/frontend/.env.local"

log() { printf '\033[0;36m▶ %s\033[0m\n' "$1"; }

# 1. Identity ---------------------------------------------------------------
if ! stellar keys address "$IDENTITY" >/dev/null 2>&1; then
  log "Creating + funding identity '$IDENTITY' on $NETWORK"
  stellar keys generate "$IDENTITY" --network "$NETWORK" --fund
fi
DEPLOYER="$(stellar keys address "$IDENTITY")"
log "Deployer: $DEPLOYER"

# 2. Build ------------------------------------------------------------------
log "Building contracts"
stellar contract build

# 3. Upload campaign WASM ---------------------------------------------------
log "Uploading campaign WASM"
CAMPAIGN_WASM_HASH="$(stellar contract upload \
  --wasm "$WASM_DIR/campaign.wasm" \
  --source "$IDENTITY" --network "$NETWORK")"
log "Campaign WASM hash: $CAMPAIGN_WASM_HASH"

# 4. Deploy factory ---------------------------------------------------------
# Upload first, then deploy by hash. Testnet is eventually consistent, so the
# freshly uploaded WASM may not be visible to the deploy simulation yet — retry.
log "Uploading factory WASM"
FACTORY_WASM_HASH="$(stellar contract upload \
  --wasm "$WASM_DIR/factory.wasm" \
  --source "$IDENTITY" --network "$NETWORK")"

log "Deploying factory"
FACTORY_ID=""
for attempt in 1 2 3 4 5; do
  if FACTORY_ID="$(stellar contract deploy \
    --wasm-hash "$FACTORY_WASM_HASH" \
    --source "$IDENTITY" --network "$NETWORK" \
    -- \
    --admin "$DEPLOYER" \
    --campaign_wasm_hash "$CAMPAIGN_WASM_HASH" 2>/dev/null)"; then
    break
  fi
  log "  deploy not ready yet (attempt $attempt), retrying in 5s…"
  sleep 5
done
[ -n "$FACTORY_ID" ] || { echo "Factory deploy failed after retries"; exit 1; }
log "Factory: $FACTORY_ID"

# 5. Test USDC token (SAC) --------------------------------------------------
log "Deploying test USDC asset (SAC)"
USDC_ID="$(stellar contract asset deploy \
  --asset "USDC:$DEPLOYER" \
  --source "$IDENTITY" --network "$NETWORK")"
log "USDC token: $USDC_ID"

# 6. Frontend env -----------------------------------------------------------
RPC_URL="https://soroban-testnet.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
if [ "$NETWORK" != "testnet" ]; then
  RPC_URL="${RPC_URL_OVERRIDE:-$RPC_URL}"
  PASSPHRASE="${PASSPHRASE_OVERRIDE:-$PASSPHRASE}"
fi

mkdir -p "$ROOT/frontend"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/deploy.sh — do not edit by hand.
VITE_NETWORK=$NETWORK
VITE_RPC_URL=$RPC_URL
VITE_NETWORK_PASSPHRASE=$PASSPHRASE
VITE_FACTORY_ID=$FACTORY_ID
VITE_USDC_ID=$USDC_ID
VITE_USDC_ISSUER=$DEPLOYER
EOF

log "Wrote $ENV_FILE"
echo
echo "Done. Next:"
echo "  • Mint test USDC:  ./scripts/mint.sh <recipient-address> 1000"
echo "  • Run frontend:    cd frontend && npm install && npm run dev"
